### ISSUE TITLE
Cannot read property 'isLast' of null at HTMLVideoElement.onNativePlaybackEnded (dash.all.debug.js:33484)

### ISSUE THREAD

**Issue by tiberiumihai** [videogular/ngx-videogular#30]
### Description
Changing video bitrate doesn't work with encrypted dash stream using ClearKey.
```
ERROR TypeError: Cannot read property 'isLast' of null
    at HTMLVideoElement.onNativePlaybackEnded (dash.all.debug.js:33484)
```

### Expected Behavior
Changing video bitrate should work wiith encrypted dash mpd.

### Actual Behavior
Receiving error:
```
ERROR TypeError: Cannot read property 'isLast' of null
    at HTMLVideoElement.onNativePlaybackEnded (dash.all.debug.js:33484)
```

### Steps to Reproduce
1. mpd used:
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.8.0-rev0-g6b4ab4012-HEAD  at 2020-09-15T21:42:31.145Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M29.096S" maxSegmentDuration="PT0H0M4.011S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264" xmlns:cenc="urn:mpeg:cenc:2013">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>playlist.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M29.096S">
  <AdaptationSet segmentAlignment="true" lang="eng" startWithSAP="1">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="17c8ad9b-1fdd-e535-9d66-6903b0564336"/>
   <SegmentTemplate media="playlist_segment_audio-encrypted$Number$.m4s" initialization="playlist_segment_audio-encryptedinit.mp4" timescale="48000" startNumber="1" duration="192000"/>
   <Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="249752">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="30000/1001" par="16:9" lang="und" startWithSAP="1">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="17c8ad9b-1fdd-e535-9d66-6903b0564336"/>
   <Representation id="2" mimeType="video/mp4" codecs="avc3.64002A" width="1920" height="1080" frameRate="30000/1001" sar="1:1" bandwidth="3664024">
    <SegmentTemplate media="playlist_segment_video-1080p-FullHD-encrypted$Number$.m4s" initialization="playlist_segment_video-1080p-FullHD-encryptedinit.mp4" timescale="30000" startNumber="1" duration="120000"/>
   </Representation>
   <Representation id="3" mimeType="video/mp4" codecs="avc3.64002A" width="1280" height="720" frameRate="30000/1001" sar="1:1" bandwidth="2061368">
    <SegmentTemplate media="playlist_segment_video-720p-HD-encrypted$Number$.m4s" initialization="playlist_segment_video-720p-HD-encryptedinit.mp4" timescale="30000" startNumber="1" duration="120000"/>
   </Representation>
   <Representation id="4" mimeType="video/mp4" codecs="avc3.64002A" width="852" height="480" frameRate="30000/1001" sar="640:639" bandwidth="1251672">
    <SegmentTemplate media="playlist_segment_video-480p-SD-encrypted$Number$.m4s" initialization="playlist_segment_video-480p-SD-encryptedinit.mp4" timescale="30000" startNumber="1" duration="120000"/>
   </Representation>
   <Representation id="5" mimeType="video/mp4" codecs="avc3.64002A" width="640" height="360" frameRate="30000/1001" sar="1:1" bandwidth="642328">
    <SegmentTemplate media="playlist_segment_video-360p-encrypted$Number$.m4s" initialization="playlist_segment_video-360p-encryptedinit.mp4" timescale="30000" startNumber="1" duration="120000"/>
   </Representation>
   <Representation id="6" mimeType="video/mp4" codecs="avc3.64002A" width="426" height="240" frameRate="30000/1001" sar="640:639" bandwidth="421032">
    <SegmentTemplate media="playlist_segment_video-240p-encrypted$Number$.m4s" initialization="playlist_segment_video-240p-encryptedinit.mp4" timescale="30000" startNumber="1" duration="120000"/>
   </Representation>
   <Representation id="7" mimeType="video/mp4" codecs="avc3.64002A" width="256" height="144" frameRate="30000/1001" sar="1:1" bandwidth="195240">
    <SegmentTemplate media="playlist_segment_video-144p-encrypted$Number$.m4s" initialization="playlist_segment_video-144p-encryptedinit.mp4" timescale="30000" startNumber="1" duration="120000"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```
2. Set default video bitrate to 480p;
3. Playback autoplays (with any of the video bitrate if provided by default).
4. Manually change the video bitrate using the video-bitrate-selector component.
5. Playback is stopped and error occurs in Chrome:
```
ERROR TypeError: Cannot read property 'isLast' of null
    at HTMLVideoElement.onNativePlaybackEnded (dash.all.debug.js:33484)
```
6. Playback is stopped and error occurs in Firefox:
```
Media resource blob:http://localhost:8080/2a0cd123-b88c-9449-8c32-e63881a072a1 could not be decoded.
This error message will be blank when privacy.resistFingerprinting = true.  If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SeekPromise> mozilla::MediaSourceTrackDemuxer::DoSeek(const mozilla::media::TimeUnit &): manager is detached. dash.all.debug.js:35437
This error message will be blank when privacy.resistFingerprinting = true.  If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - RefPtr<MediaSourceTrackDemuxer::SeekPromise> mozilla::MediaSourceTrackDemuxer::DoSeek(const mozilla::media::TimeUnit &): manager is detached. dash.all.debug.js:35438
Media resource blob:http://localhost:8080/2a0cd123-b88c-9449-8c32-e63881a072a1 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: RefPtr<MediaSourceTrackDemuxer::SeekPromise> mozilla::MediaSourceTrackDemuxer::DoSeek(const mozilla::media::TimeUnit &): manager is detached.
```

### Attachments
If needed I can provide a full archive with mpd and mp4, m4s and m4a files.

**Comment by IxquitilisSaid** [comment]
On it! Also, I cannot stress enough how happy this description makes me (steps to reproduce and all :o )
Will update you once it's fixed 😄

**Comment by tiberiumihai** [comment]
Btw: I just tested in a sample project with dashjs@3.1.3 (without ngx-videogular) and changing bitrate is working fine. I suppose there were some changes added in dashjs@3 that fixed this one.

I've upgraded to latest ngx-videogular@2.0.1 and to latest dashjs@3.1.3.

Now the steam works and autoplays. But still I can not change the video bitrate.

```
ERROR TypeError: this.dash.getAutoSwitchQualityFor is not a function
```

dashjs changed the way the bitrate is changed. More here: https://github.com/Dash-Industry-Forum/dash.js/issues/3027

To make it work with dashjs@3.1.3, we need to change `getAutoSwitchQualityFor` call with:
```
player.updateSettings({ 'streaming': { 'abr': { 'autoSwitchBitrate': { 'video': yourBouleanValue } } } });
````

**Comment by IxquitilisSaid** [comment]
Yeah, I ran into that shortly after replying to you yesterday and using Dash's typings for debugging (and people say TS is overkill, tsc tsc...).
Already updated the method(s) and the unit tests ran fine but I'll write some more just to be sure and test with a local project juuust to be sure. If everything is peachy, I'll publish a minor bump + update docs (maybe a major if we don't want to support DashJS 2.X.X) today evening, latest tomorrow early morning.

Once again, [thank you](https://i.giphy.com/media/26DMTEijJDudzovvO/giphy.webp) for raising this issue, taking time off your day to write an ultra-detailed ticket and testing/debugging it! 😄

**Comment by IxquitilisSaid** [comment]
Published! And sorry for the delay.
